METHOD_GET = 'GET'
METHOD_HEAD = 'HEAD'
METHOD_POST = 'POST'
METHOD_PUT = 'PUT'
METHOD_DELETE = 'DELETE'
METHOD_CONNECT = 'CONNECT'
METHOD_OPTIONS = 'OPTIONS'
METHOD_TRACE = 'TRACE'

HTTP_METHODS = [
    METHOD_GET,
    METHOD_HEAD,
    METHOD_POST,
    METHOD_PUT,
    METHOD_DELETE,
    METHOD_CONNECT,
    METHOD_OPTIONS,
    METHOD_TRACE
]